# Generated by Django 5.0.1 on 2024-01-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_library_book_number_of_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library_book',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
