# Generated by Django 5.0.1 on 2024-01-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_alter_library_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library_book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
