# Generated by Django 5.0.1 on 2024-01-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_alter_library_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='library_book_catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_book_catalog', models.CharField(max_length=20)),
            ],
        ),
    ]
